### ISSUE TITLE
21.5.0 > Permission RECEIVE_BOOT_COMPLETED removed

### ISSUE THREAD

**Issue by agrobost** [dandar3/android-google-play-services-ads-lite#2]
I am developing my application on Unity and I have experienced several crashes after the update of AdMob ad network. The reason is that the RECEIVE_BOOT_COMPLETED permission has been removed. 

`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" tools:node="remove" />`

What is the reason for this and can you revert it back to the way it was before? Thank you.

Sincerely.

**Comment by dandar3** [comment]
I see it has been added in 21.5.0 with the attribute for manifest merger to be removed indeed:
https://github.com/dandar3/android-google-play-services-ads-lite/commit/9efed42222c6eb431994704db0023b6429d70c20#diff-90f0a3019e1c91cfede9d4eaf5d6527ba4925d0a5ae75e97b71dfd96d365773e

I don't know the exact reason and I don't know if the sources are public to see the commits, but I found this thread relating to Ads SDK and it mentions Unity as well and it is possible it was removed on request.
https://groups.google.com/g/google-admob-ads-sdk/c/2OXYkWnMmI0?pli=1

I don't know if the manifest merger would remove it or not if added to the AndroidManifest.xml in your app, but if needed as a workaround I would suggest when cloning it down to remove the `tools:node` attribute maybe? Normally I don't alter Google's code when making this available here on GitHub as Eclipse Android libraries, it's done by an automated script I wrote, sorry I can't make the change here in this project for everyone.

Please let me know if you found a solution that works for you, might be helpful for others reading this thread.

**Comment by dandar3** [comment]
The only somewhat related mention in Ads SDK release notes page for version 21.5.0 and it suggests adding it to your `AndroidManifest.xml`:
https://developers.google.com/admob/android/rel-notes

> Removed the RECEIVE_BOOT_COMPLETED permission from the androidx.work:work-runtime dependency. If you're using Gradle versions earlier than 7.2.0 and require permission for your app, you may need to declare permission explicitly in your Android manifest.

**Comment by agrobost** [comment]
On the Unity framework, after the automatic merge of manifests during build, the RECEIVE_BOOT_COMPLETED permission is removed, leading to crashes in production. I find it unusual that a third-party module would remove Android permissions without explicit instruction to do so. To fix the issue, I reverted to the previous version of Admob.

**Comment by dandar3** [comment]
I understand what you mean, but you you don't say whether you have tried adding RECEIVE_BOOT_COMPLETED to _your app_ or not. maybe with `tools:node` with `merge` or `replace` value if it doesn't work without the attribute, to get the manifest merger to keep it.
https://developer.android.com/studio/build/manage-manifests

If you're cloning this project down the easiest thing in my view would have been to just remove the `tools:node=remove` from `AndroidManifest.xml` in the commit I mentioned above, but sure going back to previous version should work as well I guess.

Sorry I can't help you any further, I prefer to not have to make changes to Google's code cause I would have to adjust my script to do so or worse to remember to keep making these changes manually every time, making it harder for me to keep porting new versions here. 

I think you have a least one workaround above or if you prefer you can raise your issue with Google Play Services team on a the Google Groups forum linked above, maybe they will adjust their solution, although I doubt they will.

Closing this ticket, sorry.
